### ISSUE TITLE
[Bug]: WhatsApp wrong message count

### ISSUE THREAD

**Issue by victorbnl** [ferdium/ferdium-recipes#230]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-recipes/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-recipes/issues) for a feature request that matches the one I want to file, without success.

### Ferdium Version

6.2.1-nightly.39

### Recipe Name

whatsapp

### Recipe Version

3.4.6

### Steps to reproduce

Just create a WhatsApp service and use it I guess (I think it's due to updates to the website and not specific to my setup)

### Expected Behavior

The message count shows the correct count which is in my case 0 messages

### Actual Behavior

The message count shows 88 messages

### Screenshots

![image](https://user-images.githubusercontent.com/39555268/201209608-2d3cb716-508d-4b95-92c0-0ee971f7b8fe.png)

**Comment by victorbnl** [comment]
Update : the count isn't stuck at 88 but starts at this number and increments. I now have two messages so it now shows 90

**Comment by cino** [comment]
@victorbnl Is this something you would be able to debug? As this would be really hard to debug without experiencing the same issue.

**Comment by victorbnl** [comment]
It is indeed. I tried to understand how the script works and it seems that it:

1. looks for the first div[aria-label] which is indeed the chat list, no problem here
2. looks for each span[aria-label], converts its content to an int using `Ferdium.safeParseInt` and adds it to the counter

The issue could be that not only is the new message count a span[aria-label], the name and last message excerpt are too

![image](https://user-images.githubusercontent.com/39555268/201416320-65283588-7638-4e04-86d5-6e245feff122.png)

So for each chat `Ferdium.safeParseInt("Chat name")` and `Ferdium.safeParseInt("Chat last message excerpt")` are added to Ferdium's counter

But again this is from my understanding of how the script works. Also maybe it would help to know what `Ferdium.safeParseInt("string without number")` does

**Comment by nathanaelhoun** [comment]
I can confirm that before, only the message count for each conversation had a `aria-label`, and it's why we used this selector to find the number of message for each conversation.
I think they added `aria-label`s to each part now, it''s why

> Also maybe it would help to know what `Ferdium.safeParseInt("string without number")` does
@victorbnl `Ferdium.safeParseInt("string without number")` returns 0 when the string doesn't start with a number. In my case, some of my conversation are phone numbers, and so `Ferdium.safeParseInt("+33 6 79 xx xx xx")` returns `33`.

Updating the selector in the script to `div[role="gridcell"] > span > div > span[aria-label]` works for me, and select only the numbers of unread messages in each conversation. I'll open a PR :-)

**Comment by cino** [comment]
![image](https://user-images.githubusercontent.com/2735602/201467344-56f46c5a-d5c7-42aa-b543-a4c23fada971.png)

Just woke up to this, so looks like it's rolling out slowly, will test the PR.

**Comment by MichalPodeszwa** [comment]
Just to shed some light, until about 5 minutes ago I've been using Ferdi. This particular issue was the reason I've looked into Ferdi again and realized it's unmaintained and found this project.
This issue has become present there in the last couple of days, so it might be something related to WhatsApp changes internally?

**Comment by victorbnl** [comment]
I have two conversations with phone numbers which start by respectively 33 and 55 which sum is indeed 88, so I can confirm this is the issue!

**Comment by AGCaesar** [comment]
I have the same issue. I get a 3 or 4 digit number of unread messages, in reality it is 0. The number changes when I scroll through my contact list.

**Comment by ursie** [comment]
Exactly ... I can confirm as soon the message start with a number that number is added to the unread counter of the whatsapp icon. When I archive that specific chat the unread counter disappears again (because  it is zero).

Tried to apply the fix as being suggested **nathanaelhoun** but I couln't get it to work. I run Ferdium on a mac and I edited the file whatsapp.tar.gz in directory /Applications/Ferdium.app/Contents/Resources/app.asar.unpacked/recipes but that didn't solve the problem.

**Comment by Alphrag** [comment]
> Tried to apply the fix as being suggested **nathanaelhoun** but I couln't get it to work. I run Ferdium on a mac and I edited the file whatsapp.tar.gz in directory /Applications/Ferdium.app/Contents/Resources/app.asar.unpacked/recipes but that didn't solve the problem.
If you want to apply it without building, you can modify the file in `~/Library/Application Support/Ferdium/recipes/whatsapp/webview.js`. Then, simply reload the service and the changes will be applied. Let us know if that patch works for you 🙂

**Comment by ursie** [comment]
> div[role="gridcell"] > span > div > span[aria-label]

afaik see and test this fix works for me. I have scrolled through my conversations and the unread counter stays on the number as it should be.

**Comment by notapelican** [comment]
> I can confirm that before, only the message count for each conversation had a `aria-label`, and it's why we used this selector to find the number of message for each conversation. I think they added `aria-label`s to each part now, it''s why
> 
> > Also maybe it would help to know what `Ferdium.safeParseInt("string without number")` does
> 
> @victorbnl `Ferdium.safeParseInt("string without number")` returns 0 when the string doesn't start with a number. In my case, some of my conversation are phone numbers, and so `Ferdium.safeParseInt("+33 6 79 xx xx xx")` returns `33`.
> 
> Updating the selector in [the script](https://github.com/ferdium/ferdium-recipes/blob/main/recipes/whatsapp/webview.js#L19) to `div[role="gridcell"] > span > div > span[aria-label]` works for me, and select only the numbers of unread messages in each conversation. I'll open a PR :-)

Thank you! That worked for getting rid of the fake numbers.
But now I'm not getting any whatsapp unread message numbers at all... Any ideas?

**Comment by cedricroijakkers** [comment]
I found out the issue also happens if:
- You get a message from someone (either in a group or directly) that starts with a number
- You get a message from someone that is not in your contact list (i.e. their name will start with a number)
- Someone not in your contact list does something in a group (i.e. their name will start with a number)

Archiving conversations with these cases solves the issue for now.

**Comment by pacstah** [comment]
> I found out the issue also happens if:
> 
>     * You get a message from someone (either in a group or directly) that starts with a number
> 
>     * You get a message from someone that is not in your contact list (i.e. their name will start with a number)
> 
>     * Someone not in your contact list does something in a group (i.e. their name will start with a number)
> 
> 
> Archiving conversations with these cases solves the issue for now.

If you don't want to archive your chats, you can also add the people to your contact list from whom you received that last message.

**Comment by notapelican** [comment]
> I found out the issue also happens if:
> 
> * You get a message from someone (either in a group or directly) that starts with a number
> * You get a message from someone that is not in your contact list (i.e. their name will start with a number)
> * Someone not in your contact list does something in a group (i.e. their name will start with a number)
> 
> Archiving conversations with these cases solves the issue for now.

That worked for me! Question is though - I'm running multiple whatsapp accounts and for some reason 2/3 of them don't recognise contacts in my phone so they stay as regular numbers... Any ideas? More of a whatsapp issue than a ferdi/ferium one tbh

**Comment by cedricroijakkers** [comment]
> More of a whatsapp issue than a ferdi/ferium one tbh

It's still a Ferdium issue, the final fix should be in the WhatsApp recipe. That is being worked on (see https://github.com/ferdium/ferdium-recipes/pull/235), but for now, you can use the archive trick as a workaround.

**Comment by ysoudy** [comment]
Other fix : modify the file : AppData\Roaming\Ferdium\recipes\whatsapp\webview.js
and edit the line 18 :
const unreadSpans = parentChatElem.querySelectorAll('span[aria-label]:not(span[aria-label=""])');

**Comment by cedricroijakkers** [comment]
To sum up, you can it by changing line 18 to:

`const unreadSpans = parentChatElem.querySelectorAll('span[aria-label]:not(span[aria-label=""])');`

On Windows, in `C:\User\yourusername\AppData\Roaming\Ferdium\recipes\whatsapp\webview.js`
On macOS, in `~/Library/Application Support/Ferdium/recipes/whatsapp/webview.js`
On Linux, in `~/.config/Ferdium/recipes/whatsapp/webview.js`

**Comment by akira28** [comment]
@cedricroijakkers thanks for this! A question, when Ferdi will eventually fix the issue, the recipe will be automatically updated with the fix?

**Comment by Alphrag** [comment]
> @cedricroijakkers thanks for this! A question, when Ferdium will eventually fix the issue, the recipe will be automatically updated with the fix?

Unfortunately no. Currently recipes are only received through the app itself, which means that we need to push a release for that to happen (which we will because this is important enough). But we don't want to push anything until we find a fix that works for everyone as sadly, none of the previous solutions are completely fullproof so far.

As a side note, changing this behaviour to allow recipe updates without app updates is part of some long term goal, but for that we first need to [refactor the servers](https://github.com/ferdium/ferdium-server/pull/47) (both the `ferdium-server` at api.ferdium.org and the local server running in accountless mode by the app), which is a big task and takes time.

**Comment by flodi** [comment]
Probably I'm just writing some nonsense, but I've noticed that in the root pseudo class is defined a "--notification-info-icon" which is used in the classes that define the styles of the unread count. I do not know Electron, but maybe there is a way to intercept that without using the classes that - given the strange names - may change at any times.

**Comment by dgcst** [comment]
The solution of changing line 19 on the `webview.js` file works for me as well, so maybe that is in fact the solution? @Alphrag

**Comment by SpecialAro** [comment]
> The solution of changing line 19 on the `webview.js` file works for me as well, so maybe that is in fact the solution? @Alphrag

This solution was tested and doesn't work for some folks (e.g for @vraravam).

**Comment by MazzMat** [comment]
Me too with stable release

Version: 6.2.0
Server: No Server
Electron: 20.2.0
Chrome: 104.0.5112.124
Node.js: 16.15.0
Platform: macOS Monterey
Arch: arm64
Build date: Thu Sep 22 2022 18:47:30 GMT+0200 (Ora legale dell’Europa centrale)
Git SHA: https://github.com/ferdium/ferdium-app/commit/84613b5b6821fe37f3f9c17df5640d57b9a8f071
Git branch: release

**Comment by MazzMat** [comment]
Changing line 19 remove the wrong badge number but I don't see any badge for Whatsapp service

**Comment by ysoudy** [comment]
I'm the author of the fix.
The problem is Ferdium is looking all topics subjects and messages.
So if someone send to you 1234 in the conversation, you will have +1234 in the red bubble ;p

You can try an other fix (always the line #18) 👍 
`const unreadSpans = parentChatElem.querySelectorAll('span.ovhn1urg');`

It's a better fix, because need less CPU to count the new messages

**Comment by nathanaelhoun** [comment]
> You can try an other fix (always the line #18) 👍 `    const unreadSpans = parentChatElem.querySelectorAll('span.ovhn1urg');     `
> It's a better fix, because need less CPU to count the new messages
@ysoudy 

The `span.ovhn1urg` selector will probably change with the next WhatsApp update, as it is a CSS class name that is compiled and minified by their build tool.

We need to find a solution that could survive WhatsApp's updates. #237 tries to guess this compiled class name, but it doesn't work for everyone's whatsapp version yet.

**Comment by akatarmo** [comment]
> I'm the author of the fix. The problem is Ferdium is looking all topics subjects and messages. So if someone send to you 1234 in the conversation, you will have +1234 in the red bubble ;p
> 
> You can try an other fix (always the line #18) +1 `    const unreadSpans = parentChatElem.querySelectorAll('span.ovhn1urg');     
> 
> It's a better fix, because need less CPU to count the new messages

I can confirm, for me the **two fix** that you have developed work, even though I am using the second one. This:

	const unreadSpans = parentChatElem.querySelectorAll('span.ovhn1urg');   

Thanks !!!

**Comment by leandrogehlen** [comment]
The badges count continues wrong

![image](https://user-images.githubusercontent.com/1750751/203037518-69818ebd-24c6-4ec2-9fd8-3334a7b2de21.png)

**Comment by akatarmo** [comment]
It works fine for me. What is the fix that you have applied?

**Comment by akatarmo** [comment]
> I'm the author of the fix. The problem is Ferdium is looking all topics subjects and messages. So if someone send to you 1234 in the conversation, you will have +1234 in the red bubble ;p
> 
> You can try an other fix (always the line #18) +1 `    const unreadSpans = parentChatElem.querySelectorAll('span.ovhn1urg');     `
> 
> It's a better fix, because need less CPU to count the new messages

I'm using this fix in webview.js

const unreadSpans = parentChatElem.querySelectorAll('span[aria-label]:not(span[aria-label=""])');

**Comment by SpecialAro** [comment]
> The badges count continues wrong
> 
> ![image](https://user-images.githubusercontent.com/1750751/203037518-69818ebd-24c6-4ec2-9fd8-3334a7b2de21.png)

This is working as expected. Unread messages from muted chats don't count for the count.

**Comment by leandrogehlen** [comment]
i'm sorry, i did not pay attention

**Comment by calvinwyoung** [comment]
@leandrogehlen How did you apply the latest version of the recipe? Did you have to clone it locally?

**Comment by Alphrag** [comment]
> This is working as expected. Unread messages from muted chats don't count for the count.

Hmm, it should show a blue dot as indirect message anyway...

 

> How did you apply the latest version of the recipe? Did you have to clone it locally?

@calvinwyoung It has been shipped on the last nightlies but if you are using the stable release and want that fix in before the next update for you, you can modify the `webview.js` file of that recipe by hand (right-click on whatsapp then `Edit -> Open user.js` to get to the appropriate location if you don't know where that is).

**Comment by akatarmo** [comment]
> @Gaibhne What version of the service are you using (you can see it at the bottom in the edit window)? If it is not 3.4.7, you can either wait to get it, or manually put the fix from #240.

I have tried to update to v3.4.7 but it is quite confusing to determine how many and which are the **exact files** that I have to edit/replace.  I have done it following the link,

https://github.com/ferdium/ferdium-recipes/pull/240

but it doesn't work, it doesn't mark the number of unread messages, so I have to go back to the second manual fix that worked for me, posted by **ysoudy** above

**Comment by Glennmen** [comment]
How do we get this fix? (Without needing to manually change values)
An update recipes button would be useful 😅

**Comment by Alphrag** [comment]
> How do we get this fix? (Without needing to manually change values) An update recipes button would be useful sweat_smile

At the moment you can't just update the recipe directly at the moment ([cf my previous answer](https://github.com/ferdium/ferdium-recipes/issues/230#issuecomment-1315082313) about that). So either you wait for the release or you get your hands just a bit dirty by updating the `webview.js` file yourself.

 @akatarmo The best way is to take the updated [`webview.js` file in the repo](https://github.com/ferdium/ferdium-recipes/blob/main/recipes/whatsapp/webview.js) and to replace your old one by this one if you want to manually get exactly the change introduced. If that doesn't solve the problem, then that fix is unfortunately not enough and we need to dig a bit deeper (as the fix you mention will definitely break again on a next update from whatsapp).

**Comment by akatarmo** [comment]
Hi, @Alphrag

Thanks, **everything is fine now**, with the file you have put in the link.

https://github.com/ferdium/ferdium-recipes/blob/main/recipes/whatsapp/webview.js

I don't know where the hell I copied-pasted a **webview.js** with 98 lines (when it should have 80) that I understood was the new one.

**Comment by Gaibhne** [comment]
Thank you, the fix from the PR seems to be working so far. One question: now that I have manually updated my recipe, will it still auto-update on the next release ? If not, what must I do to go back to stock once the release version has the PR ?

**Comment by Alphrag** [comment]
> now that I have manually updated my recipe, will it still auto-update on the next release ?

When you update the app, it looks at the version of all the services you are using and compare them with the version packaged within the app. If the packaged version is higher, it will replace the files of the local recipe with the one from the app. So, as long as you do not change the version number in the `package.json` file of the recipe, updates will propagate normally when new versions are happening.

**Comment by nathanaelhoun** [comment]
Hi @akatarmo,
I think your issue is the one fixed in https://github.com/ferdium/ferdium-recipes/pull/247, but I can't be sure.
Since it's not link to this current issue (wrong message count on Whatsapp), I encourage you to create a new issue for your bug if it persists.

**Comment by akatarmo** [comment]
Hello, thanks for answering @nathanaelhoun

This receipe 3.4.8  https://github.com/ferdium/ferdium-recipes/pull/247

fixed the logging problem, but the wrong message counter problem came back again. After installing and uninstalling several times, finally with receipe 3.4.7 it works again, I don't know how or why.

**Comment by SpecialAro** [comment]
I'm reopening this issue given that I too have the same problem with the message count again with the latest recipe (3.4.8).

**Comment by hakanalpp** [comment]
> I'm reopening this issue given that I too have the same problem with the message count again with the latest recipe (3.4.8).

Same here, with Fedora 36 and 3.4.8 recipe

**Comment by SpecialAro** [comment]
Hey @hakanalpp thank you for trying to help out!

After talking with @Alphrag and @vraravam I concluded that this was a problem with my local, manly related to some toggle being off which previously wasn't (this is an known issue that users will face in the next stable release most likely).

As a future reference for anyone checking this issue, make sure you have this toggle on!
![image](https://user-images.githubusercontent.com/37463445/204115837-d986d9c7-2a33-4596-86ec-808f13d04561.png)

I'm closing this issue back again as the cause of the issue is not related to the WA message count.

**Comment by peteracworth** [comment]
the fix has worked for me on windows 10 and 11  (change line 19 in webview.js to const unreadSpans = parentChatElem.querySelectorAll('span[aria-label]:not(span[aria-label=""])');    )

Version: 6.2.0
Server: Ferdium Server
Electron: 20.2.0
Chrome: 104.0.5112.124
Node.js: 16.15.0
Platform: Windows 11
Arch: x64
Build date: Thu Sep 22 2022 10:13:21 GMT-0700 (Pacific Daylight Time)
Git SHA: 84613b5b
Git branch: release

**Comment by phiexz** [comment]
seems like new recipe also counting **Archived** chat.
is there a way to skip counting **archived** chat?

**Comment by sellout** [comment]
I am still dealing with this issue (I see a badge with “927”). I _think_ I have done all the right things:

* Ferdium 6.2.7, on macOS Ventura 13.3.1, installed via Homebrew;
* “Show unread message badges” is enabled; and
* I have no archived chats (I did, but they had no unreads, then I deleted them all, toggled “Show unread message badges”, restarted Ferdium, etc.).

The problem appears to be that the WhatsApp service settings says “Recipe version 3.4.5”, when at least 3.4.7 is required for this to be fixed.

Considering I’m on the current version of Ferdium, why do I not have the latest recipies? I actually uninstalled/re-installed Ferdium to see if that would do it, but no luck.

The console has a lot of messages about Ferdium. I could help diagnose if I knew what to look for. In particular, these four lines repeat every 5 seconds:
```
error	14:48:24.501276-0600	kernel	System Policy: Ferdium(36800) deny(1) file-read-data /Users/greg/Library/DoNotDisturb/DB/ModeConfigurations.json
default	14:48:24.501615-0600	Ferdium	Failed to open \M-q\M-lD\M-q\^A, error Error Domain=NSCocoaErrorDomain Code=257 "The file “ModeConfigurations.json” couldn’t be opened because you don’t have permission to view it." UserInfo={NSFilePath=/Users/greg/Library/DoNotDisturb/DB/ModeConfigurations.json, NSUnderlyingError=0x149197c60 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}
error	14:48:24.502166-0600	kernel	System Policy: Ferdium(36800) deny(1) file-read-data /Users/greg/Library/DoNotDisturb/DB/Assertions.json
default	14:48:24.502593-0600	Ferdium	Failed to open \M-q\M-lD\M-q\^A, error Error Domain=NSCocoaErrorDomain Code=257 "The file “Assertions.json” couldn’t be opened because you don’t have permission to view it." UserInfo={NSFilePath=/Users/greg/Library/DoNotDisturb/DB/Assertions.json, NSUnderlyingError=0x14c89ff90 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}
``` 

Copying the latest webview.js contents into my local one “fixed” it, but the problem I’m concerned about is not having current recipes in general. How do I know if they’re out of date (without having to look up a bug)? Is it possible to force a fetch of the new versions and get an error if updating them fails?

**Comment by vraravam** [comment]
Recipes are bundled within the Ferdium installer and so are auto-upgraded only with each new nightly/beta/stable release of the app. There's a [discussion thread](https://github.com/ferdium/ferdium-app/discussions/824) about decoupling this behavior so that the recipes can be independently released and upgraded without having to upgrade the app itself. As with other ideas, there aren't any contributors who are working on this atm

**Comment by Yelizaroff** [comment]
> Hi, @Alphrag
> 
> Thanks, **everything is fine now**, with the file you have put in the link.
> 
> https://github.com/ferdium/ferdium-recipes/blob/main/recipes/whatsapp/webview.js
> 
> I don't know where the hell I copied-pasted a **webview.js** with 98 lines (when it should have 80) that I understood was the new one.

Thank you! I found a solution on my MacBookPro M1 in Sonoma.

Go to folder:
~\Library\Application Support\Franz\recipes\whatsapp

Rename file webview.js as webview._old.js 

Download & replace file with this file: [webview.js](https://github.com/ferdium/ferdium-recipes/blob/main/recipes/whatsapp/webview.js)

Restart Franz.

Good Luck for all!!
