### ISSUE TITLE
[Bug]: Occasional WhatsApp (Left-hand-side) search problem.

### ISSUE THREAD

**Issue by n00b42** [ferdium/ferdium-recipes#91]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-recipes/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-recipes/issues) for a feature request that matches the one I want to file, without success.

### Ferdium Version

6.0.0-nightly.74

### Recipe Name

whatsapp

### Recipe Version

3.4.1

### Steps to reproduce

Open WA service, press on left-hand search field.

### Expected Behavior

Focus WA search field and allow to search.

### Actual Behavior

Sometimes it focuses some "secondary" text field or so.
- This overlaps with the actual search field
- Entered Text does not do anything
- Pressing enter just focuses the current chat.

### Screenshots

![ferdium-wa2](https://user-images.githubusercontent.com/6792900/176636076-65734059-1db7-4e85-975d-033e110fc934.png)

### Additional Information

Note: "Sometimes" - can not reliable pinpoint WHEN or WHY it will happen yet

**Comment by SpecialAro** [comment]
This most likely is fixed on their latest update.. They changed the UI of the search, so probably they also fixed that bug 
![image](https://user-images.githubusercontent.com/37463445/178033772-c97247a6-1b16-4db3-a703-3c1c81e0e7fd.png)

**Comment by VaiTon** [comment]
Can confirm that this is still happening on latest beta `6.0.0-beta.3`

**Comment by SpecialAro** [comment]
Closing this as there aren't any reports of this issue in the stable versions. If needed, comment bellow to reopen, thank you very much.
